**Importing libraries**

In [ ]:
import tensorflow as tf

### Create Tensors

In [ ]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(123, tf.int16)
floating = tf.Variable(3.45, tf.float16)

print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.45>


### Rank/Degree of Tensor

In [ ]:
rank1_tensor = tf.Variable(["this is a string"], tf.string)
print(rank1_tensor)

rank2_tensor = tf.Variable([["this is a string", "ok"],\
                            ["this is also a string","yes"]], tf.string)
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'this is a string'], dtype=object)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'this is a string', b'ok'],
       [b'this is also a string', b'yes']], dtype=object)>


In [ ]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
tf.rank(tf.Variable([["Yes"],["No"]], tf.string))

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### Shape of Tensor

In [ ]:
string.shape, number.shape, floating.shape

(TensorShape([]), TensorShape([]), TensorShape([]))

In [ ]:
rank1_tensor.shape, rank2_tensor.shape

(TensorShape([1]), TensorShape([2, 2]))

In [ ]:
(tf.Variable([["Yes"],["No"]], tf.string)).shape

TensorShape([2, 1])

### Reshape

In [ ]:
tensor1 = tf.ones([1,2], tf.int16)
print(tensor1)

tf.Tensor([[1 1]], shape=(1, 2), dtype=int16)


In [ ]:
tensor2 = tf.reshape(tensor1, [2,1])
print(tensor2)

tf.Tensor(
[[1]
 [1]], shape=(2, 1), dtype=int16)
