**Importing libraries**

In [1]:
import tensorflow as tf

**Create Tensors**

In [2]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(123, tf.int16)
floating = tf.Variable(3.45, tf.float16)

print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.45>


2022-10-04 12:34:38.960813: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-04 12:34:39.059254: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


Rank/Degree of Tensor

In [3]:
rank1_tensor = tf.Variable(["this is a string"], tf.string)
print(rank1_tensor)

rank2_tensor = tf.Variable([["this is a string", "ok"], ["this is also a string","yes"]], tf.string)
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'this is a string'], dtype=object)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'this is a string', b'ok'],
       [b'this is also a string', b'yes']], dtype=object)>


In [4]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [5]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [6]:
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [7]:
tf.rank(tf.Variable([["Yes"],["No"]], tf.string))

<tf.Tensor: shape=(), dtype=int32, numpy=2>

**Shape of Tensor**

In [8]:
string.shape, number.shape, floating.shape

(TensorShape([]), TensorShape([]), TensorShape([]))

In [9]:
rank1_tensor.shape, rank2_tensor.shape

(TensorShape([1]), TensorShape([2, 2]))

In [10]:
(tf.Variable([["Yes"],["No"]], tf.string)).shape

TensorShape([2, 1])

**Reshape**

In [11]:
tensor1 = tf.ones([1,2], tf.int16)
print(tensor1)

tf.Tensor([[1 1]], shape=(1, 2), dtype=int16)


In [12]:
tensor2 = tf.reshape(tensor1, [2,1])
print(tensor2)

tf.Tensor(
[[1]
 [1]], shape=(2, 1), dtype=int16)
